import type { Metadata } from "next";

import "./globals.css";
import React from "react";
import {cn} from "@/lib/utils";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" className="h-full">
      <body className={cn("relative h-full antialised ")}>
      <main className="relative flex flex-col min-h-screen">
         <div className="flex-grow flex-1"> {children}</div>
      </main>

      </body>

      </html>
  );
}
